apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/skyglass-books/catalog-service/k8s?ref=master

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/skyglass-books/catalog-service
  newTag: 5a84d61944bf1d7a6356f89df3f595d0b7d689a1

replicas:
- count: 2
  name: catalog-service
