apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/skyglass-books/edge-service/k8s?ref=master

patchesStrategicMerge:
- patch-env.yml
- patch-ingress.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/skyglass-books/edge-service
  newTag: 992e4b4b86dd2a797b913f831972f2d4a7f4b685

replicas:
- count: 1
  name: edge-service
